hotel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views



urlpatterns = [
	path('admin/', admin.site.urls),
	
	path('accounts/login/', auth_views.LoginView.as_view(
		template_name='login.html'), name="login"),
	path('accounts/logout/', auth_views.LogoutView.as_view(
		template_name='logout.html'), name="logout"),
	path('', include('visitors.urls')),
	


]

visitors/urls.py
from django.urls import path

from . import views

app_name = 'visitors'
urlpatterns = [
	path('', views.index, name='index'),
	path('bookings/', views.bookings, name='bookings'),

]

visitors/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# class User(models.Model):
#     '''To do: implement this model'''
#     first_name = models.CharField(max_length=200)
#     last_name = models.CharField(max_length=200)
#     phone_number = models.IntegerField()


class Room(models.Model):

	room_number = models.CharField(max_length=200)
	price = models.IntegerField()

class Booking(models.Model):

	room = models.ForeignKey(Room, on_delete=models.CASCADE)
	customer = models.ForeignKey(User, on_delete=models.CASCADE)
	start_date = models.DateField()
	end_date = models.DateField()

visitors/forms.py
from django import forms
from django.forms import ModelForm

from .models import User


class UserForm(ModelForm):
   
	model = User
	fields = ['first_name', 'last_name', 'phone_number']
  

visitors/views.py
from django.shortcuts import render
from .models import User
from .forms import UserForm


def index(request):
	return render(request, 'index.html')

def bookings(request):
	if request.method == 'POST':
		post = request.POST
		first_name = post['first_name']
		last_name = post['last_name']
		phone_number = post['phone_number']
	   
		user = User(first_name=first_name, last_name=last_name, 
			phone_number=phone_number)

		user.save()

	return render(request, 'bookings.html')

def show_vacancies():
	pass

visitors/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
 
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">




<title>{% block title %}hotel Torquay{% endblock %}</title>
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <a class="navbar-brand" href="{% url 'visitors:index' %}">Home</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-item nav-link" href="{% url 'visitors:bookings' %}">Bookings</a><span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">contact us</a>
      </li>
    </ul>
  </div>
</nav>
 
  {% block content %}{% endblock %}
</body>
</html>

visitors/templates/bookings.html
{% extends "base.html" %}
{% block content %}




  <div class="container">
    <div class="row">
      <div class="col-8 offset-4">
          <div class="card-header">
            <h1 class="text-center">Book a Room</h1>
          </div>

          <div class="card-body">
            <form method="POST">
              {% csrf_token %}
              <label>First Name</label>
              <input class="form-control" type="text" name="first_name">

              <label class="mt-4">Last Name</label>
              <input class="form-control" type="text" name="last_name">

              <label class="mt-4">Phone Number</label>
              <input class="form-control" type="text" name="phone_number">

              <label class="mt-4">Start Date</label>
              <input class="form-control" type="text" name="start_date">

              <label class="mt-4">End Date</label>
              <input class="form-control" type="text" name="end_date">

              <label class="mt-4">Room</label>
              <input class="form-control" type="text" name="room">




              <button type="submit" class="btn btn-outline-primary btn-block mt-4">Submit</button>
            </form>
          </div>
        </div>
    </div>
  </div>






{% endblock %}

visitors/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %} 

<div class="container">
    <div class="row">
    	<div class="col-8 offset-2">
    		<h1>Hotel Torquay</h1>
    		<img src="{% static 'media/Cypress.jpg' %}">
    	</div>
    	<div class="col-2">	

      	<img src="{% static 'media/calendar.gif' %}">
      	
    	 
		
  </div>
</div>






{% endblock %}

visitors/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

  <div class="row mt-3">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      {% if form.errors %}
      <p>Your username and password didn't match. Please try again.</p>
      {% endif %}

      {% if next %}
        {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
        please login with an account that has access.</p>
        {% else %}
        <p>Please login to see this page.</p>
        {% endif %}
      {% endif %}
      <form method="post" action="{% url 'login' %}">
        {% csrf_token %}
        <table>
          <tr>
            <td class="m-3">{{ form.username.label_tag }}</td>
            <td>{{ form.username }}</td>
          </tr>
          <tr>
            <td class="m-3">{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
          </tr>
        </table>

        <input type="submit" value="login">
        <input type="hidden" name="next" value="{{ next }}">
      </form>
    </div>
    <div class="col-md-3"></div>
  </div>
</div>

{% endblock %}